/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiennmpc04188_it17304_assignment_gd2;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author Admin
 */
public class TrangChu extends javax.swing.JFrame {

    
    public TrangChu() {
        initComponents();
        lblDangNhap.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        lblLienHe = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblGioiThieu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pnl3 = new javax.swing.JPanel();
        pnlTranChu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pnlGioiThieu = new javax.swing.JPanel();
        pnlLienHe = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(0, 0, 0));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Nhà Sách mooi");
        pnl1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.jpg"))); // NOI18N
        pnl1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        lblDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_dang-nhap.png"))); // NOI18N
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });
        pnl1.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 160, 50));

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLienHe.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblLienHe.setText("Liên Hệ");
        lblLienHe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLienHeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLienHeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLienHeMouseExited(evt);
            }
        });
        pnl2.add(lblLienHe, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lblTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTrangChu.setText("Trang chủ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseExited(evt);
            }
        });
        pnl2.add(lblTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblGioiThieu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblGioiThieu.setText("Giới Thiệu");
        lblGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseExited(evt);
            }
        });
        pnl2.add(lblGioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton2.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        getContentPane().add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 900, 80));

        pnl3.setBackground(new java.awt.Color(0, 204, 204));
        pnl3.setLayout(new java.awt.CardLayout());

        pnlTranChu.setBackground(new java.awt.Color(102, 153, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ SÁCH", "TÊN SÁCH", "THỂ LOẠI", "TÁC GIẢ", "GIÁ"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout pnlTranChuLayout = new javax.swing.GroupLayout(pnlTranChu);
        pnlTranChu.setLayout(pnlTranChuLayout);
        pnlTranChuLayout.setHorizontalGroup(
            pnlTranChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTranChuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlTranChuLayout.setVerticalGroup(
            pnlTranChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTranChuLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pnl3.add(pnlTranChu, "card_TrangChu");

        pnlGioiThieu.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout pnlGioiThieuLayout = new javax.swing.GroupLayout(pnlGioiThieu);
        pnlGioiThieu.setLayout(pnlGioiThieuLayout);
        pnlGioiThieuLayout.setHorizontalGroup(
            pnlGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        pnlGioiThieuLayout.setVerticalGroup(
            pnlGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        pnl3.add(pnlGioiThieu, "card_GioiThieu");

        pnlLienHe.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout pnlLienHeLayout = new javax.swing.GroupLayout(pnlLienHe);
        pnlLienHe.setLayout(pnlLienHeLayout);
        pnlLienHeLayout.setHorizontalGroup(
            pnlLienHeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        pnlLienHeLayout.setVerticalGroup(
            pnlLienHeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        pnl3.add(pnlLienHe, "card_LienHe");

        getContentPane().add(pnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 900, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        CardLayout layout = (CardLayout)pnl3.getLayout();
        layout.show(pnl3,"card_TrangChu");
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseEntered
        lblTrangChu.setOpaque(true);
        lblTrangChu.setBackground(Color.white);
        lblTrangChu.setForeground(pnl3.getBackground());
    }//GEN-LAST:event_lblTrangChuMouseEntered

    private void lblTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseExited
        lblTrangChu.setOpaque(true);
        lblTrangChu.setBackground(pnl2.getBackground());
        lblTrangChu.setForeground(Color.black);
    }//GEN-LAST:event_lblTrangChuMouseExited

    private void lblGioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseClicked
        CardLayout layout = (CardLayout)pnl3.getLayout();
        layout.show(pnl3,"card_GioiThieu");
    }//GEN-LAST:event_lblGioiThieuMouseClicked

    private void lblGioiThieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseEntered
        lblGioiThieu.setOpaque(true);
        lblGioiThieu.setBackground(Color.white);
        lblGioiThieu.setForeground(pnl3.getBackground());
    }//GEN-LAST:event_lblGioiThieuMouseEntered

    private void lblGioiThieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseExited
        lblGioiThieu.setOpaque(true);
        lblGioiThieu.setBackground(pnl2.getBackground());
        lblGioiThieu.setForeground(Color.black);
    }//GEN-LAST:event_lblGioiThieuMouseExited

    private void lblLienHeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLienHeMouseClicked
        CardLayout layout = (CardLayout)pnl3.getLayout();
        layout.show(pnl3,"card_LienHe");
    }//GEN-LAST:event_lblLienHeMouseClicked

    private void lblLienHeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLienHeMouseEntered
        lblLienHe.setOpaque(true);
        lblLienHe.setBackground(Color.white);
        lblLienHe.setForeground(pnl3.getBackground());
    }//GEN-LAST:event_lblLienHeMouseEntered

    private void lblLienHeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLienHeMouseExited
        lblLienHe.setOpaque(true);
        lblLienHe.setBackground(pnl2.getBackground());
        lblLienHe.setForeground(Color.black);
    }//GEN-LAST:event_lblLienHeMouseExited

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDangNhapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblLienHe;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnlGioiThieu;
    private javax.swing.JPanel pnlLienHe;
    private javax.swing.JPanel pnlTranChu;
    // End of variables declaration//GEN-END:variables
}
